const contractAddress = "0x7927923F20F421645D66033686C2dD8f654F0Be7"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the 'Alien Grunts'' NFT Project!!"; 
const welcome_h2 = "Connect to Coinbase or MetaMask to Get Started";
const welcome_p = "The 'Alien Grunts' NFT Project is the second stop on DJ SHADOWMIND's NFT Roadmap.";
const h1_presale_coming_soon = "Alien Grunts NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Alien Grunts";
const h2_presale_coming_soon = "Pre-Sale Mint Countdown";
const h2_presale_mint = "Public Mint Countdown";
const p_presale_coming_soon = "Almost There. Visit DJShadowmind.Com for more Music and NFT Info";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale.";
const p_presale_mint_already_minted = "You've already claimed your maximum mints. Thank you!";
const p_public_mint = "Alien Grunts Public Mint Has Started";
const button_presale_coming_soon = "Visit Us For More Information on Twitter";
const button_presale_mint_whitelisted = "Mint Your Alien Grunts NFT";
const button_presale_mint_not_whitelisted = "Visit Us For More Information on Twitter";
const button_presale_already_minted = "Visit Us For More Information on Twitter";
const button_public_mint = "Mint Your Alien Grunt NFT";
const mint_failed = "Minting failed. There was a rip in the time/space continuum. Please try again.";